name: Publish Extension

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: 'Bump version'
        required: true
        default: 'patch'
        options:
          - 'major'
          - 'minor'
          - 'patch'
          - 'none'
      update_docs:
        type: boolean
        description: 'Docs are up to date'
        required: true
        default: false

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Install deps
      run: npm install
      
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    
    - name: Publish extension
      env:
        NODE_ENV: 1
      run: npx @vscode/vsce publish ${{inputs.version}} -p ${{secrets.MARKETPLACE_TOKEN}} --allow-star-activation

    - name: Commit and push version change
      run: |
        git push --follow-tags https://VSC-NeuroPilot:${{secrets.GITHUB_TOKEN}}:@github.com/VSC-NeuroPilot/neuropilot
    
    - name: Rebuild docs site
      if: ${{ inputs.update_docs }}
      run: gh workflow run bump.yml -f check=${{ inputs.update_docs }} --repo VSC-NeuroPilot/docs

