name: Publish Extension

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: 'Bump version'
        required: true
        default: 'patch'
        options:
          - 'major'
          - 'minor'
          - 'patch'
          - 'none'
      update_docs:
        type: boolean
        description: 'Docs are up to date'
        required: true
        default: false

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Bump docs version
      if: ${{ inputs.update_docs }}
      run: |
        cd docs
        npm version --no-git-tag-version ${{ inputs.version }}
        git add package.json package-lock.json

    - name: Build
      run: |
        npm install
        npm run compile
      
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    
    - name: Publish extension
      run: npx @vscode/vsce publish ${{inputs.version}} -p ${{secrets.MARKETPLACE_TOKEN}} --allow-star-activation --no-git-tag-version

    - name: Commit and push version change
      run: |
        new_version=$(npm show ./ version)
        git commit -am "$new_version"
        git tag -a "v$new_version" -m "$new_version"
        git push --follow-tags https://VSC-NeuroPilot:${{secrets.GITHUB_TOKEN}}:@github.com/VSC-NeuroPilot/neuropilot
