name: Tests (Desktop & Web)

on:
    push:
        branches:
            - master
            - dev
    # Tests should always run on Pull Requests in order to catch regressions early
    pull_request:
    workflow_dispatch: # in case we need to regenerate test coverage

jobs:
    desktop-tests:
        name: Desktop (Electron) tests
        strategy:
            fail-fast: false
            matrix:
                include:
                  - os: macos-latest
                    name: macOS
                  - os: windows-latest
                    name: Windows
                  - os: ubuntu-latest
                    name: Linux
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Cache VS Code test downloads
              uses: actions/cache@v4
              with:
                key: neuropilot-tests-vscode-${{ github.repository }}-${{ matrix.os }}
                path: .vscode-test/
            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10.14.0
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 22.x
                cache: 'pnpm'
                cache-dependency-path: './pnpm-lock.yaml'
            - run: npm install
            - name: Run desktop tests (Linux)
              run: xvfb-run -a pnpm run test:desktop
              if: runner.os == 'Linux'
            - name: Run desktop tests (macOS/Windows)
              run: pnpm run test:desktop
              if: runner.os != 'Linux'
            # for now we'll stop with this
            # VSC-NeuroPilot/actions/send-test-repo-action will be added later

    web-tests:
        name: Web tests (Chromium headless)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10.14.0
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 22.x
                cache: 'pnpm'
                cache-dependency-path: './pnpm-lock.yaml'
            - run: npm install
            - name: Run web tests (headless browser)
              run: pnpm run test:web:browser
    #test-web:
    #    name: Web tests
    #    strategy:
    #      fail-fast: false
    #      matrix:
    #        include:
    #            - engine: webkit
    #              browser: Safari
    #            - engine: firefox
    #              browser: Firefox
    #            - engine: chromium
    #              browser: Chrome
    #    runs-on: ubuntu-latest
